spring:
  jackson:
    default-property-inclusion: non_null
  web:
    resources:
      #控制api文档访问, smart-doc生成的html静态api文档，生产服务器不需要暴露文档
      add-mappings: off
  #开发环境启用thymeleaf的缓存
  thymeleaf:
    cache: on
  #nacos server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8087
  zipkin:
    base-url: http://192.168.40.132:9411
    discovery-client-enabled: off
    sender:
      type: web
  sleuth:
    sampler:
      #设置采样率为100%(性能会降低)，默认为0.1，10的采样率
      probability: 0.1
  #使用spring session redis存储session信息
  session:
    store-type: redis
    timeout: 30m
  redis:
    database: 0
    host: 192.168.40.132
    port: 6379
    password: 123456
    timeout: 6000ms
#乐璟商城-线程池配置
lejing:
  thread:
    #核心线程池数量
    core-pool-size: 50
    #最大线程数
    maximum-pool-size: 300
    #时间单位代表-秒
    time-unit: seconds
    #存活时间
    keep-alive-time: 10
    #最大任务数量
    capacity: 200000
