spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.105:3306/lejing_wms?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
  web:
    resources:
      #控制api文档访问, smart-doc生成的html静态api文档
      add-mappings: on
  rabbitmq:
    host: 192.168.31.105
    port: 5672
    username: lejing
    password: 123456
    virtual-host: /lejing
    template:
      #只要消息抵达Queue，就会异步发送优先回调return-confirm
      mandatory: on
    #开启发送端消息抵达Broker确认
    publisher-confirm-type: correlated
    #开启发送端消息抵达Queue确认
    publisher-returns: on
    listener:
      simple:
        #手动ack确认消息，不使用默认的消费端确认
        acknowledge-mode: manual
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.105:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.31.105:8087
    alibaba:
      seata:
        # seata 服务分组，要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应
        tx-service-group: lejing_tx_group
  zipkin:
    base-url: http://192.168.31.105:9411
    discovery-client-enabled: off
    sender:
      type: web
  sleuth:
    sampler:
      #设置采样率为100%(性能会降低)，默认为0.1，10的采样率
      probability: 1
#seata 配置
seata:
  enabled: on
  application-id: ${spring.application.name}
  tx-service-group: ${spring.cloud.alibaba.seata.tx-service-group}
  enable-auto-data-source-proxy: on
  registry:
    type: nacos
    nacos:
      application: seata-server
      group: SEATA_GROUP
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      namespace: 'f1c51b7c-562f-48c8-9b15-3a0ebd25dc2d'
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      group: SEATA_GROUP
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      namespace: 'f1c51b7c-562f-48c8-9b15-3a0ebd25dc2d'
      username: nacos
      password: nacos
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#运费配置
lejing:
  fee:
    postage: 12
