server:
  port: 12000
  shutdown: graceful

spring:
  main:
    allow-circular-references: true
  application:
    name: lejing-search
  profiles:
    #运行环境: dev|test|prod
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: '*'
#feign sentinel
feign:
  sentinel:
    enabled: on
