spring:
  mail:
    host: "default"
    username: "username"
    password: "password"
    protocol: "smtp"
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    # 多邮件模板配置列表
    email-templates:
      - template-name: EmailQQ
        mail-properties:
          host: "smtp.qq.com"
          username: "username"
          password: "password"
          protocol: "smtp"
          properties:
            mail:
              smtp:
                ssl:
                  enable: true
      - template-name: Email163
        mail-properties:
          host: "smtp.163.com"
          username: "username"
          password: "password"
          protocol: "smtp"
          properties:
            mail:
              smtp:
                ssl:
                  enable: true