spring:
  mail:
    host: "smtp.163.com"
    port: 443
    username: "username"
    password: "password"
    protocol: "smtp"
    # 开启安全连接
    properties:
      mail:
        smtp:
          ssl:
            enable: true

    # 多邮件模板配置列表
    email-templates:
      - template-name: EmailQQ
        mail-properties:
          host: "smtp.qq.com"
          port: 80
          username: "username"
          password: "password"
          protocol: "smtp"
          properties:
            mail:
              smtp:
                ssl:
                  enable: true
      - template-name: Email163
        mail-properties:
          host: "smtp.163.com"
          port: 456
          username: "username"
          password: "password"
          protocol: "smtp"
          properties:
            mail:
              smtp:
                ssl:
                  enable: true
