spring:
  mail:
    host: "smtp.189.cn"
    port: 465
    username: "xxx@189.cn"
    password: "your_password"
    protocol: "smtp"
    properties:
      mail:
        smtp:
          ssl:
            enable: true
        debug: false
    #邮件线程池配置
    thread:
      core-pool-size: 50
      maximum-pool-size: 200
      keep-alive-time: 10
      time-unit: seconds
      capacity: 2000
    # 多邮件模板配置列表
    email-templates:
      - template-name: EmailQQ
        mail-properties:
          host: "smtp.qq.com"
          port: 465
          username: "xxx@qq.com"
          password: "your_password"
          protocol: "smtp"
          properties:
            mail:
              smtp:
                ssl:
                  enable: true
              debug: false
      - template-name: EmailOffice365
        mail-properties:
          host: "smtp.office365.com"
          port: 587
          username: "xxx@outlook.com"
          password: "your_password"
          protocol: "smtp"
          properties:
            mail:
              smtp:
                starttls:
                  enable: true
              debug: false
      - template-name: Email163
        mail-properties:
          host: "smtp.163.com"
          port: 587
          username: "xxx@163.com"
          password: "your_password"
          protocol: "smtp"
          properties:
            mail:
              smtp:
                ssl:
                  enable: true
              debug: false
