logging:
  level:
    cn.alphahub.mall.order.excel.easypoi: trace
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.40.132:3306/lejing_oms?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
  web:
    resources:
      #控制api文档访问, smart-doc生成的html静态api文档
      add-mappings: on
  #redis配置
  redis:
    host: 192.168.40.132
    port: 6379
    password: 123456
    database: 0
  #nacos server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 192.168.40.132
    port: 5672
    username: lejing
    password: 123456
    virtual-host: /lejing
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#乐璟商城参数配置
lejing:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    time-unit: seconds
    keep-alive-time: 10
    capacity: 10000
