server:
  port: 9008
  shutdown: graceful

spring:
  application:
    name: lejing-order-easypoi
  profiles:
    #运行环境: dev|test|prod
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml,mapper/**/*Dao.xml
  type-aliases-package: com.**.order.domain,cn.**.order.domain,com.**.order.entity,cn.**.order.entity
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ASSIGN_ID:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID"
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
# PageHelper分页插件
pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
