spring:
  jackson:
    default-property-inclusion: non_null
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8087
      scg:
        fallback:
          response-status: 400
          content-type: 'application/json;charset=UTF-8'
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
