spring:
  jackson:
    default-property-inclusion: non_null
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8087
      scg:
        fallback:
          response-status: 400
          content-type: 'application/json;charset=UTF-8'
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  zipkin:
    base-url: http://192.168.40.132:9411
    discovery-client-enabled: off
    sender:
      type: web
  sleuth:
    sampler:
      #设置采样率为100%(性能会降低)，默认为0.1，10的采样率
      probability: 0.1
