server:
  port: 88
spring:
  application:
    name: lejing-gateway
  profiles:
    #运行环境: dev|test|prod
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        #第1个路由
        - id: bd_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        #第2个路由
        - id: qq_route
          uri: https://im.qq.com
          predicates:
            - Query=url,qq
