spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:884
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8087
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
