spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.140:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.31.140:8087
      scg:
        fallback:
          response-status: 400
          content-type: 'application/json;charset=UTF-8'
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  zipkin:
    base-url: http://192.168.31.140:9411
    discovery-client-enabled: off
    sender:
      type: web
  sleuth:
    sampler:
      #设置采样率为100%(性能会降低)，默认为0.1，10的采样率
      probability: 1
