server:
  port: 25000
spring:
  application:
    name: lejing-seckill
  profiles:
    #运行环境: dev|test|prod
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss
management:
  endpoints:
    web:
      exposure:
        include: '*'
