spring:
  web:
    resources:
      #控制api文档访问, smart-doc生成的html静态api文档
      add-mappings: on
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.106:3306/lejing_ums?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.106:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.31.106:8087
  zipkin:
    base-url: http://192.168.31.106:9411
    discovery-client-enabled: off
    sender:
      type: web
  sleuth:
    sampler:
      #设置采样率为100%(性能会降低)，默认为0.1，10的采样率
      probability: 1
  thymeleaf:
    cache: off
  #使用spring session redis存储session信息
  session:
    store-type: redis
    timeout: 30m
  #redis配置
  redis:
    host: 192.168.31.106
    port: 6379
    password: 123456
    database: 0
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
