server:
  port: 8090
  shutdown: graceful

spring:
  application:
    name: lejing-site-reserve
  profiles:
    #运行环境: dev|test|prod
    active: dev
    #加载common工程配置文件 'application-email.yml' 邮件配置元数据, spring.profiles.include: email
    include: email
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml,mapper/**/*Dao.xml
  type-aliases-package: com.**.domain,cn.**.domain,com.**.entity,cn.**.entity
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ASSIGN_ID:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID"
      id-type: assign_id
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
# PageHelper分页插件
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
