server:
  port: 7000
spring:
  application:
    name: lejing-coupon
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml,mapper/**/*Dao.xml
  type-aliases-package: com.**.domain,cn.**.domain,com.**.entity,cn.**.entity
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: on
#全局跨域设置
cors:
  config:
    #是否允许所有域名跨域：true|false
    is-allows-all-domain: false
    #允许跨域的域名集合
    allowed-origins:
      - http://127.0.0.1:7000
      - http://api.alphahub.cn
      - http://www.alphahub.cn