server:
  port: 10000
spring:
  application:
    name: lejing-product
  profiles:
    #运行环境: dev|test|prod
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss
  #开启Redis缓存
  cache:
    type: redis
    redis:
      #缓存的过期时间，1天
      time-to-live: 1d
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml,mapper/**/*Dao.xml
  type-aliases-package: com.**.product.domain,cn.**.product.domain,com.**.product.entity,cn.**.product.entity
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID"
      id-type: auto
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
# PageHelper分页插件
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
management:
  endpoints:
    web:
      exposure:
        include: '*'
#feign sentinel
feign:
  sentinel:
    enabled: on
