spring:
  web:
    resources:
      #控制api文档访问, smart-doc生成的html静态api文档，生产服务器不需要暴露文档
      add-mappings: off
  jackson:
    default-property-inclusion: non_null
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.40.132:3306/lejing_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  #生产环境禁用thymeleaf的缓存
  thymeleaf:
    cache: on
  #使用spring session redis存储session信息
  session:
    store-type: redis
    timeout: 30m
  #redis配置
  redis:
    host: 192.168.40.132
    port: 6379
    password: 123456
    client-name: LEJING_REDIS
    # Redisson settings
    # Tips:
    #     Use Redisson through spring bean with RedissonClient interface or RedisTemplate/ReactiveRedisTemplate objects
    # path to config - redisson.yml
    redisson:
      file: classpath:redisson-single.yml
logging:
  level:
    cn.alphahub.mall.product: info
#乐璟商城-线程池配置
lejing:
  thread:
    #核心线程池数量
    core-pool-size: 50
    #最大线程数
    maximum-pool-size: 300
    #时间单位代表-秒
    time-unit: seconds
    #存活时间
    keep-alive-time: 10
    #最大任务数量
    capacity: 200000
