spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.140:3306/lejing_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  ##多数据源的配置
  #dynamic:
  #  datasource:
  #    slave1:
  #      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #      url: jdbc:sqlserver://localhost:1433;DatabaseName=renren_security
  #      username: sa
  #      password: 123456
  #    slave2:
  #      driver-class-name: org.postgresql.Driver
  #      url: jdbc:postgresql://localhost:5432/renren_security
  #      username: renren
  #      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.140:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.31.140:8087

  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 192.168.31.140
    port: 6379
    password: 123456
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
