spring:
  web:
    resources:
      #控制api文档访问, smart-doc生成的html静态api文档，生产服务器不需要暴露文档
      add-mappings: off
  thymeleaf:
    cache: on
  jackson:
    default-property-inclusion: non_null
  cloud:
    nacos:
      #配置中心
      config:
        #namespace做环境隔离
        namespace: acae20ec-5e2b-4e9e-92bb-cb985a7e0f9e
        server-addr: 192.168.31.116:8848
        refresh-enabled: true
        #垃圾nacos特么居然严格区分yaml和yml
        file-extension: yml
        extension-configs:
          - data-id: datasource.yml
            group: dev
            refresh: true
          - data-id: mybatis.yml
            group: dev
            refresh: true
          - data-id: common.yml
            group: DEFAULT_GROUP
            refresh: true
