spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.105:3306/lejing_job?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#指定要生成代码的数据库类型, 可选值: MYSQL, ORACLE, SQLSERVER, POSTGRESQL, MONGODB
code:
  generator:
    db-type: MYSQL

#mongodb:
#  host: localhost
#  port: 27017
#  auth: false #是否使用密码验证
#  username: admin
#  password: 123456
#  source: 123456
#  database: mongodb_test
